name: demo

on:
  schedule:
  - cron: "*/5 * * * *"
  
jobs:
  add-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run script
        run: python add_time.py
      - name: Push changes to GitHub
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.DEMO_WORKFLOW }}
          script: |
            git add .
            git commit -m "Update at $(date +%Y-%m-%d %H:%M:%S)"
            git push
