name: demo

on:
  schedule:
  - cron: "*/5 * * * *"
  
jobs:
  add-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run script
        run: python add_time.py
      - name: Setup git config
        run: |
          # Setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          # Inspired by https://lannonbr.com/blog/2019-12-09-git-commit-in-actions/
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "'date'"
          git push
